export const FETCH_TODOS = "FETCH_TODOS";
export const FETCH_SINGLE_TODO = "FETCH_SINGLE_TODO";
export const TOGGLE_COMPLETE_TODO = "TOGGLE_COMPLETE_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const ADD_TODO = "ADD_TODO";
